source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Core Libraries
def core()
  pod 'Alamofire-Gloss', :path => '../'
end

# Testing Libraries
def testing()
  pod 'Quick'
  pod 'Nimble'
end

target 'Demo' do
  platform :ios, '9.0'
  core
end

target 'Tests' do
  platform :ios, '9.0'
  core
  testing
end

